# Form implementation generated from reading ui file 'designer/client_documents_list.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DocumentsList(object):
    def setupUi(self, DocumentsList):
        DocumentsList.setObjectName("DocumentsList")
        DocumentsList.resize(775, 590)
        self.verticalLayout = QtWidgets.QVBoxLayout(DocumentsList)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=DocumentsList)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.scrollArea = QtWidgets.QScrollArea(parent=DocumentsList)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 751, 498))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.documents_list = QtWidgets.QListWidget(parent=self.scrollAreaWidgetContents)
        self.documents_list.setObjectName("documents_list")
        self.horizontalLayout_2.addWidget(self.documents_list)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.create_button = QtWidgets.QPushButton(parent=DocumentsList)
        self.create_button.setObjectName("create_button")
        self.horizontalLayout.addWidget(self.create_button)
        self.view_doc_button = QtWidgets.QPushButton(parent=DocumentsList)
        self.view_doc_button.setObjectName("view_doc_button")
        self.horizontalLayout.addWidget(self.view_doc_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(DocumentsList)
        QtCore.QMetaObject.connectSlotsByName(DocumentsList)

    def retranslateUi(self, DocumentsList):
        _translate = QtCore.QCoreApplication.translate
        DocumentsList.setWindowTitle(_translate("DocumentsList", "Form"))
        self.label.setText(_translate("DocumentsList", "Мои заявки"))
        self.create_button.setText(_translate("DocumentsList", "Создать"))
        self.view_doc_button.setText(_translate("DocumentsList", "Перейти к заявке"))
